(mapc #'acknowledge-function
      '("EXTRACT-LAMBDA-LIST"
        "EXTRACT-SPECIALIZER-NAMES"
        "SET-FUNCALLABLE-INSTANCE-FUNCTION"
        "STANDARD-INSTANCE-ACCESS"
        "FUNCALLABLE-STANDARD-INSTANCE-ACCESS"
        "COMPUTE-APPLICABLE-METHODS-USING-CLASSES"
        "REMOVE-DIRECT-METHODS"))

(mapc #'acknowledge-setf-function
      '("STANDARD-INSTANCE-ACCESS"
        "FUNCALLABLE-STANDARD-INSTANCE-ACCESS"))
